# Generated by Django 5.2.1 on 2025-05-16 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clima', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ciclo', models.CharField(help_text='Ej: anual, bianual, permanente', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.CharField(help_text='Zona o lote agrícola', max_length=100)),
                ('superficie_ha', models.FloatField(help_text='Superficie cultivada en hectáreas')),
                ('fecha_siembra', models.DateField()),
                ('fecha_inicio_cosecha', models.DateField()),
                ('fecha_fin_cosecha', models.DateField()),
                ('cantidad_obtenida', models.FloatField(help_text='Producción total')),
                ('unidad', models.CharField(help_text='kg, ton, etc.', max_length=10)),
                ('rendimiento', models.FloatField(blank=True, help_text='Rendimiento por hectárea', null=True)),
                ('fertilizante_usado', models.CharField(blank=True, max_length=100)),
                ('cantidad_fertilizante', models.FloatField(blank=True, help_text='Cantidad de fertilizante total (kg, litros...)', null=True)),
                ('pesticida_usado', models.CharField(blank=True, max_length=100)),
                ('cantidad_pesticida', models.FloatField(blank=True, null=True)),
                ('agua_utilizada_m3', models.FloatField(blank=True, help_text='Volumen total de agua usada', null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('clima_fin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosechas_fin', to='clima.lecturaclima')),
                ('clima_inicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosechas_inicio', to='clima.lecturaclima')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='cosechas.cultivo')),
            ],
        ),
    ]
