# Generated by Django 5.2.1 on 2025-05-19 01:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
        ('cosechas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosecha',
            options={'ordering': ['-fecha_fin_cosecha'], 'verbose_name': 'Cosecha', 'verbose_name_plural': 'Cosechas'},
        ),
        migrations.AlterModelOptions(
            name='cultivo',
            options={'ordering': ['nombre'], 'verbose_name': 'Cultivo', 'verbose_name_plural': 'Cultivos'},
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='agua_utilizada_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volumen total de agua (m³)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='cantidad_fertilizante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='cantidad_obtenida',
            field=models.DecimalField(decimal_places=2, help_text='Producción total', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='cantidad_pesticida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='parcela',
            field=models.CharField(help_text='Lote agrícola', max_length=100),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Producción / ha', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='superficie_ha',
            field=models.DecimalField(decimal_places=2, help_text='Superficie sembrada (ha)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='ciclo',
            field=models.CharField(help_text='Ej.: anual, bianual, permanente', max_length=50),
        ),
        migrations.AddIndex(
            model_name='cosecha',
            index=models.Index(fields=['cultivo', 'fecha_fin_cosecha'], name='cosechas_co_cultivo_bd47f0_idx'),
        ),
        migrations.AddIndex(
            model_name='cosecha',
            index=models.Index(fields=['parcela'], name='cosechas_co_parcela_ef0cc9_idx'),
        ),
    ]
