# Generated by Django 5.2.1 on 2025-05-16 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('tipo_grano', models.CharField(help_text='Ej: café, maíz, arroz', max_length=100)),
                ('fecha_procesamiento', models.DateField()),
                ('cantidad_kg', models.FloatField(help_text='Cantidad total procesada (kg)')),
                ('humedad', models.FloatField(help_text='% de humedad')),
                ('impurezas', models.FloatField(help_text='% de impurezas')),
                ('grano_bueno', models.FloatField(help_text='% de grano sano o aprovechable')),
                ('grano_defectuoso', models.FloatField(help_text='% de grano defectuoso')),
                ('observaciones', models.TextField(blank=True)),
                ('enviado', models.BooleanField(default=False, help_text='¿Ya se envió el informe por correo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
