# Generated by Django 5.2.1 on 2025-05-19 01:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_calidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteprocesado',
            options={'ordering': ['-fecha_procesamiento', 'codigo_lote'], 'verbose_name': 'Lote Procesado', 'verbose_name_plural': 'Lotes Procesados'},
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='cantidad_kg',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad total procesada (kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='cliente',
            field=models.ForeignKey(help_text='Usuario cliente que recibe el informe', on_delete=django.db.models.deletion.CASCADE, related_name='lotes_procesados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='codigo_lote',
            field=models.CharField(db_index=True, help_text='Identificador único de lote', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo de creación'),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='enviado',
            field=models.BooleanField(default=False, help_text='Indica si se envió el informe al cliente'),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='fecha_procesamiento',
            field=models.DateField(help_text='Fecha en que se procesó el lote'),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='grano_bueno',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de grano sano (%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='grano_defectuoso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de grano defectuoso (%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='humedad',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de humedad (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='impurezas',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de impurezas (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas adicionales del análisis'),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='tipo_grano',
            field=models.CharField(choices=[('cafe', 'Café'), ('maiz', 'Maíz'), ('arroz', 'Arroz'), ('otro', 'Otro')], default='otro', help_text='Tipo de grano procesado', max_length=20),
        ),
        migrations.AddIndex(
            model_name='loteprocesado',
            index=models.Index(fields=['cliente', 'fecha_procesamiento'], name='control_cal_cliente_63a4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='loteprocesado',
            index=models.Index(fields=['codigo_lote'], name='control_cal_codigo__16548d_idx'),
        ),
    ]
