# Generated by Django 5.2.1 on 2025-05-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_calidad', '0002_alter_loteprocesado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteprocesado',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro'),
        ),
        migrations.AlterField(
            model_name='loteprocesado',
            name='enviado',
            field=models.BooleanField(default=False, help_text='Indica si el informe ha sido entregado al cliente'),
        ),
    ]
