# Generated by Django 5.2.1 on 2025-05-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('supervisor', 'Supervisor')], default='cliente', help_text='Define el nivel de acceso del usuario (cliente, admin o supervisor).', max_length=15),
        ),
    ]
