# Generated by Django 5.2.1 on 2025-05-16 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clima', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cultivo_afectado', models.CharField(max_length=100)),
                ('temporada', models.CharField(help_text='Ej: Primavera, todo el año...', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateField(auto_now_add=True)),
                ('probabilidad', models.FloatField(help_text='Porcentaje de riesgo, entre 0 y 100')),
                ('accion_recomendada', models.TextField(help_text='Ej: Aplicar pesticida, revisar zona, etc.')),
                ('generada_por_modelo', models.BooleanField(default=True)),
                ('lectura_climatica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clima.lecturaclima')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='plagas.tipoplaga')),
            ],
        ),
        migrations.CreateModel(
            name='EventoPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_detectada', models.DateField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('severa', 'Severa')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='plagas.tipoplaga')),
            ],
        ),
    ]
