# Generated by Django 5.2.1 on 2025-05-19 01:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
        ('plagas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoplaga',
            options={'ordering': ['-fecha_detectada'], 'verbose_name': 'Evento de plaga', 'verbose_name_plural': 'Eventos de plaga'},
        ),
        migrations.AlterModelOptions(
            name='prediccionplaga',
            options={'ordering': ['-fecha_prediccion'], 'verbose_name': 'Predicción de plaga', 'verbose_name_plural': 'Predicciones de plaga'},
        ),
        migrations.AlterModelOptions(
            name='tipoplaga',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de plaga', 'verbose_name_plural': 'Tipos de plaga'},
        ),
        migrations.AlterField(
            model_name='eventoplaga',
            name='severidad',
            field=models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('severa', 'Severa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prediccionplaga',
            name='probabilidad',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de riesgo entre 0 y 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tipoplaga',
            name='temporada',
            field=models.CharField(choices=[('primavera', 'Primavera'), ('verano', 'Verano'), ('otono', 'Otoño'), ('invierno', 'Invierno'), ('todo_ano', 'Todo el año')], default='todo_ano', max_length=20),
        ),
        migrations.AddIndex(
            model_name='eventoplaga',
            index=models.Index(fields=['tipo', 'fecha_detectada'], name='plagas_even_tipo_id_4c9867_idx'),
        ),
        migrations.AddIndex(
            model_name='prediccionplaga',
            index=models.Index(fields=['tipo', 'fecha_prediccion'], name='plagas_pred_tipo_id_24a494_idx'),
        ),
    ]
