# Generated by Django 5.2.1 on 2025-05-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagas', '0002_alter_eventoplaga_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccionplaga',
            name='accion_recomendada',
            field=models.TextField(help_text='Ej: Aplicar pesticida, monitorear área, etc.'),
        ),
        migrations.AlterField(
            model_name='prediccionplaga',
            name='generada_por_modelo',
            field=models.BooleanField(default=True, help_text='Si fue generada automáticamente por el modelo de IA.'),
        ),
    ]
