# Generated by Django 5.2.1 on 2025-05-18 23:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Medición', 'verbose_name_plural': 'Mediciones'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['nombre'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
        migrations.AlterField(
            model_name='medicion',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='sensores.sensor'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha/hora de lectura'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='unidad',
            field=models.CharField(help_text='Ej: °C, %, Pa, lux', max_length=20, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='nombre',
            field=models.CharField(help_text='Ej: Sensor Temperatura Invernadero', max_length=100, unique=True, verbose_name='Nombre identificador'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('presion', 'Presión'), ('luminosidad', 'Luminosidad'), ('gas', 'Gas'), ('ph', 'pH')], max_length=20, verbose_name='Tipo de sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación física/descriptiva'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['sensor', 'timestamp'], name='sensores_me_sensor__f5d286_idx'),
        ),
    ]
