# Generated by Django 5.2.1 on 2025-05-20 23:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_alter_medicion_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='rango_maximo',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Valor máximo aceptable antes de desactivar el actuador.', max_digits=8, null=True, verbose_name='Límite máximo'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='rango_minimo',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Valor mínimo aceptable antes de activar el actuador.', max_digits=8, null=True, verbose_name='Límite mínimo'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='valor_referencia',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Valor deseado de operación automática. Ej: 25.0 °C', max_digits=8, null=True, verbose_name='Valor objetivo'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='sensor',
            field=models.ForeignKey(help_text='Sensor asociado a la medición.', on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='sensores.sensor'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Fecha y hora exacta de la medición.', verbose_name='Fecha/hora de lectura'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='valor',
            field=models.DecimalField(decimal_places=3, help_text='Valor medido. Solo positivos.', max_digits=8, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el sensor sigue activo en el sistema.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró el sensor.'),
        ),
    ]
