# Generated by Django 5.2.1 on 2025-05-16 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('externo', 'Externo'), ('interno', 'Interno')], max_length=10)),
                ('ubicacion', models.CharField(help_text='Ej: Norte del invernadero, Zona 3', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LecturaClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(blank=True, help_text='°C', null=True)),
                ('humedad', models.FloatField(blank=True, help_text='%', null=True)),
                ('presion', models.FloatField(blank=True, help_text='hPa', null=True)),
                ('viento', models.FloatField(blank=True, help_text='km/h', null=True)),
                ('precipitacion', models.FloatField(blank=True, help_text='mm', null=True)),
                ('radiacion_solar', models.FloatField(blank=True, help_text='W/m²', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='clima.dispositivoclima')),
            ],
        ),
    ]
