# Generated by Django 5.2.1 on 2025-05-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivoclima',
            options={'ordering': ['nombre'], 'verbose_name': 'Dispositivo climático', 'verbose_name_plural': 'Dispositivos climáticos'},
        ),
        migrations.AlterModelOptions(
            name='lecturaclima',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Lectura climática', 'verbose_name_plural': 'Lecturas climáticas'},
        ),
        migrations.AlterField(
            model_name='dispositivoclima',
            name='ubicacion',
            field=models.CharField(help_text='Ej: Zona norte del invernadero', max_length=200),
        ),
        migrations.AddIndex(
            model_name='lecturaclima',
            index=models.Index(fields=['dispositivo', 'timestamp'], name='clima_lectu_disposi_68e28d_idx'),
        ),
    ]
